title: SWIM | Solutions for Water Integrity and Management
email: info@swimsolutions.org
description: >- # this means to ignore newlines until "baseurl:"
  We deal with water management.
baseurl: ''
permalink: /:title
# logo: /assets/images/logo.webp
sass:
  sass_dir: /assets/_sass
  # style: :compressed
collections:
  - elements
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
theme: jekyll-theme-cayman